### ISSUE TITLE
org.xmlrenderer:flying-saucer-pdf does not work with Java 9 modules

### ISSUE THREAD

**Issue by VerachtertAaron** [flyingsaucerproject/flyingsaucer#349] opened 2024-07-17 09:41 UTC
As mentioned in https://groups.google.com/g/flying-saucer-users/c/kw3FnbSIS2E, there is a package naming conflict between `org.xmlrenderer:flying-saucer-pdf` and `org.xmlrenderer:flying-saucer-core`: package `org.xhtmlrenderer.simple` is present in both jars.

This causes projects using Java 9 modules to not be able to load both dependencies correctly. The fix proposed in the google groups thread would solve this.

**Comment by andreasrosdal** [comment] 2024-07-18 11:21
Pull request welcome.

**Comment by asolntsev** [comment] 2024-07-19 16:18
@VerachtertAaron @andreasrosdal I also see package "org.xhtmlrenderer.simple" is still used in two different modules: "core" and "swt".

Shouldn't we rename the package in "swt" module as well?

<img width="402" alt="image" src="https://github.com/user-attachments/assets/00adbaf2-ced8-4e41-838b-da11b7fa2061">

**Comment by asolntsev** [comment] 2024-07-19 18:33
Fixed by https://github.com/flyingsaucerproject/flyingsaucer/pull/350 and https://github.com/flyingsaucerproject/flyingsaucer/pull/351

**Closed** 2024-07-19 18:33 UTC

**Comment by asolntsev** [comment] 2024-07-21 19:19
@VerachtertAaron Hi. Can you confirm that the problem was fixed in FS 9.9.0?

**Comment by bartbiemans** [comment] 2024-12-17 10:13
@asolntsev We updated this and the problem is indeed fixed in this version. Apologies for the late feedback and thank you for the release!
